name: Destroy AWS Environment

on: [workflow_dispatch]
  
jobs:

  destroy-environment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cdk destroy
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'destroy -f'
        working_dir: 'infra'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'